name: SetPRLabel
on:
  pull_request:
jobs:
  SetPRLabel:
    name: SetPRLabel
    runs-on: ubuntu-latest
    steps:
      - name: Set PR labels
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          dot: true
